### ISSUE TITLE
IM-pure-H2O sometimes fails to find SaturationP

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#132]
For some magma compositions the IM H2O expression can generate a negative concentration at high pressures. The current solver bounds the problem with a low and high pressure. Rarely this high pressure can generate a negative H2O concentration, causing the solver to fail. The function should have a mechanism to check for this and adjust the bounds accordingly

**Comment by kaylai** [comment]
A similar issue exists within LiuCarbon (probably LiuWater, too, but I found this while running the current test() method). If the CO2 concentration in the system is very large, LiuCarbon.calculate_equilibrium_fluid_comp() may calculate an unreal number for the amount of CO2 in the fluid. For now, I "fixed" this by checking if the number is a float and, if not, returning 0.0 as the fluid CO2. It also returns a warning "Could not find equilibrium fluid composition." 

I don't know that rebounding the solver is the right solution in this case, since this seems to only affect samples that are far outside of the compositional range of the model. But, maybe there is a better way to handle this case?

**Comment by simonwmatthews** [comment]
Fixed.
