### ISSUE TITLE
tasplot import problems

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#134]
Penny and I just discovered a bug with importing VESIcal that only appears when you haven't run `sys.path.append("../..")`. in vplot.py tasplot is imported using the statement from `tasplot.tasplot import *`, which instructs python to look to the tasplot folder in the main repo directory.

I think there are two possible solutions:
1. tasplot becomes a required dependancy that must be installed by the user. Then the import statement changes to `from tasplot import *`.
2. We move the tasplot code into the main VESIcal module directory, and then import it using `from VESIcal.tasplot import *`.

What do you think is best?

**Comment by kaylai** [comment]
Hi! Good catch. I also ran into this issue when installing the current dev_newStructure version of VESIcal on the TEST pip server. I solved it using your second method. That is, I've put the tasplot folder into VESIcal (at the same level as the models folder) with its own __init__.py file, and I've changed the import to from VESIcal.tasplot import *.

I am hoping this is non unpythonic since this is not our code, but I have left the license and README in the tasplot folder, so it is properly cited.

Commit 5f5b7bf398cd077496e0ce58dcf9761ce0164b32
