### ISSUE TITLE
calculate_degassing_path with pressure arg fails

### ISSUE THREAD

**Issue by lvanderlaat** [kaylai/VESIcal#173]
# Issue

Cannot use an array for arg `pressure`  in `calculate_degassing_path` with models `MagmaSat` and `Liu`. It does work with `Dixon` model, though. 

# code
```python
sample = v.Sample({
    'SiO2':  64.6,
    'TiO2':  0.86,
    'Al2O3': 16.4,
    'Fe2O3': 0.663327,
    'FeO': 3.3830,
    'CaO': 4.53,
    'MgO': 0.87,
    'Na2O': 4.08,
    'K2O': 1.05,
    'P2O5': 0.0105,
    'H2O': 6,
    'CO2': 0.03
})

pressure = np.arange(450, 200, -1)
df = v.calculate_degassing_path(
    sample=sample, pressure=pressure, temperature=1200,
    fractionate_vapor=0.0, model='Liu', init_vapor=2.,
).result
```

# Output

```
    open_df = v.calculate_degassing_path(
  File "/opt/anaconda3/envs/vesical/lib/python3.10/site-packages/VESIcal/calculate_classe
s.py", line 55, in __init__
    self.calib_check = self.check_calibration_range(sample=self.sample,
  File "/opt/anaconda3/envs/vesical/lib/python3.10/site-packages/VESIcal/calculate_classe
s.py", line 450, in check_calibration_range
    s = self.model.check_calibration_range(parameters)
  File "/opt/anaconda3/envs/vesical/lib/python3.10/site-packages/VESIcal/model_classes.py
", line 768, in check_calibration_range
    if cr.check(parameters) is False:
  File "/opt/anaconda3/envs/vesical/lib/python3.10/site-packages/VESIcal/calibration_chec
ks.py", line 26, in check
    return self.checkfunction(self.value,
  File "/opt/anaconda3/envs/vesical/lib/python3.10/site-packages/VESIcal/calibration_chec
ks.py", line 156, in crf_Between
    return paramval >= calibval[0] and paramval <= calibval[1]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.an
y() or a.all()
```

**Comment by kaylai** [comment]
Fascinating! Thanks for flagging this. I will take a look. I see the doc string implies this behavior (the use of an array in the pressure arg) was meant to be universal:

```
pressure     string, float, int, list, or numpy array
        Defaults to 'saturation', the calculation will begin at the saturation
        pressure. If a number is passed as either a float or int, this will be
        the starting pressure. If a list of numpy array is passed, the
        pressure values in the list or array will define the degassing path,
        i.e. final_pressure and steps variables will be ignored. Units are
        bars.
```

So, this should definitely be fixed. I can take a look.

 @simonwmatthews do you have any additional thoughts?

**Comment by kaylai** [comment]
Looking closer it looks like it's not the degassing path calculation failing but something with the calibration range check.

**Comment by simonwmatthews** [comment]
Looks to me like it is a feature that has to be supported by each model independently. At the moment MagmaSat (and Liu I guess, though I didn't check specifically) doesn't support it. The MagmaSat routine doesn't check what sort of input it is being given, and so passes the array straight to the calibration check routine, which then fails because it expects a float.

Easiest short-term bug fix would be to update the documentation to specify that feature is not universally compatible, and perhaps add an input check to MagmaSat and Liu to flag it if it gets given an array. Otherwise, it should be relatively straightforward to add it as a feature... Or perhaps we should remove it as a feature from the other models to keep consistency? What do you think?

**Comment by kaylai** [comment]
Apologies for the late reply to this. I agree this functionality is a good thing and should not be removed. I can work on integrating the behavior into MagmaSat first (which is handled differently in the code than all other models since it uses the ENKI thermoengine Python library) and then take a closer look at the other models. It might take me a week or two to get to this as I'm a bit oversubscribed at the moment, but it's a priority!

**Comment by kaylai** [comment]
I think I have fixed this for the Liu model, but I want @simonwmatthews to have eyes on this before I decide that what I've done is the proper implementation of the fix. I've initiated a pull request with Simon as a requested reviewer of the code. The current "fix" is in the branch called "DegassingPathArrayBug" at commit 9b8a81a1713b3cb6a02bfd70d966c3cb396124c0

**Comment by kaylai** [comment]
Just to update everyone interested in this. We have decided on a fix. I need to separately implement something for the MagmaSat model as it's coded up completed differently to all the other models. Working on that now. I plan to push an update to the main branch and subsequently to pip after I fix all of the models. For now, you can use `pressure` and `final_presure` args for non-MagmaSat models and `pressure` and `steps` args for MagmaSat. Not perfect I know, but I will get the fix in asap.

**Comment by kaylai** [comment]
This is fixed! I actually figured out a way to do this that makes a lot more sense than essentially nixing the crf_Between calibration checks. All I had to do was teach crf_Between how to handle if a numpy array was passed as a parameter by the user. Previously, the code would error as it could not check equality between a float and an array. I change it so that if a numpy array is passed, it checks equality on array.any(), such that crf_Between fails if any items in the array are not between the specified calibration values.

The branch where I was working on this fix has been merged into master. The bug fix will be implemented in the next version of VESIcal.

20144b6ac42a7ff3ef5a2b2b52f7dd7819c52c82
