### ISSUE TITLE
Change MixedFluid.calculate_equilibrium_fluid_comp from system total to dissolved input.

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#30]
The MixedFluid.calculate_equilibrium_fluid_comp method assumes the volatile concentrations passed in sample are the system total volatile concentrations, not the concentrations dissolved in the fluid at the conditions of interest (and why it also requires a pressure to be chosen). To make this consistent with MagmaSat it should calculate assuming the concentrations are dissolved.

There could be an option for which way the function should be run, to keep this feature. Before changing, check that other methods don't rely on this particular way of implementing the method.

**Comment by kaylai** [comment]
Actually, it sounds like it is acting just like the MagmaSat model does, which also requires pressure. MagmaSat assumes the volatiles passed refer to the entire system, not just dissolved, since it can't a priori know how much volatiles are dissolved without knowing the P and T and equilibrating the system.

**Comment by simonwmatthews** [comment]
Ok, let's leave this as it is for now.
