### ISSUE TITLE
Handling of low pressures within pure and mixed fluid models

### ISSUE THREAD

**Issue by simonwmatthews** [kaylai/VESIcal#32]
Low pressures are a source of problems. Their origins need to be constrained (perhaps scipy.optimize?) and something robust implemented to deal with it, particularly when calling functions like calculate_degassing_paths. At the moment I've hacked an inelegant solution here, but I think there will be a more robust generic way of dealing with this.

This is relatively low-priority. In the vast majority of realistic cases this will cause no problems.

**Comment by simonwmatthews** [comment]
I *think* this is fixed.

**Comment by kaylai** [comment]
Is this related to (or the same as) the issue where when calculating saturation pressure, a nan value gets passed somewhere causing the code to error? 

I am experiencing this when testing calculate_saturation_pressure() methods for Water models. To solve the problem for Liu et al, I changed the root_scalar parameters to lower values. I think there is a good rationale to do that for Liu et al, since it is calibrated to quite low pressures. I set x0=10.0 and x1=200.0.

It might be worth playing around with these values in the other models to see if this fixes erroring out at low Ps.

**Comment by simonwmatthews** [comment]
Usually when NaN values appear its because a negative pressure is being put into a logarithmic function somewhere- this was happening in the Eguchi model. This can happen if a solution doesn't exist, though hopefully that should be caught before calling the root finder. It can also happen if there's a problem with one of the expressions, such that it can't find a root. Or, the expression is sufficiently complicated that there's maxima and/or minima- in which case setting x0 and x1 should get that sorted out!
