### ISSUE TITLE
Standardize/Decide upon normalization routines

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#47]
I am thinking ahead here and wondering if, when we really get down to comparing models, some of the differences will be due to the way preprocessing is done differently per model. Some may force normalization of the sample, others not. We should at least discuss and think about this such that the "differences" in model results we see are not partly an artifact of these choices.

**Comment by gordon5m** [comment]
I agree. A good first step would be to have an outline or table of what the different preprocessing is per each model. Otherwise, it will be a bit tough to wrap our heads around the possibilities. 

====================
Gordon Moore, Ph.D.
Experimental Petrologist
Astromaterials Research & Exploration Science
Jacobs, NASA Johnson Space Center

2101 E NASA Pkwy
Mail Code XI3
Houston, TX, 77058

Office: (281) 483-1875
On-site email:  gordon.moore@nasa.gov

“All petrology, all of the time.”--

**Comment by kaylai** [comment]
Good idea! I’ll make a table.

**Comment by simonwmatthews** [comment]
My take on this is that we should aim to make the preprocessing methods change the sample composition as little as possible- only making it compatible with the method- i.e. when a method demands a particular way of normalizing. So far, where models do not normalize the input sample that's because the results are insensitive to the normalization (i.e. everything appears as a ratio). Its less clear how to include volatiles in the normalization however... This can probably be worked out by looking very closely at the data used to calibrate the model, and how that was normalized. in particular, is the composition used in calibration that before volatiles are added, or after the experiment? Perhaps one way of checking the comparison is to provide an option for the preprocessing step to be skipped. In some cases this will mean a result won't be returned (e.g. the Eguchi model when the sample has only FeOt rather than FeO and Fe2O3 listed separately), but I think this would be generally a useful way to get an idea of how much effect the preprocessing step is having?

The other thing I've been thinking about is how to expose this sort of information to the user, in principle its all accessible through the docstrings, however it requires looking at multiple docstrings (potentially) to fully understand what the method does... One way we could implement something useful is with the __repr__ special method. By defining this for each model, when the user prints the model directly (e.g. print(default_models['Dixon']) it will return a string representation of the object- we can make this string representation a concise summary of the model implementation. What are your thoughts?

**Comment by kaylai** [comment]
Sorry I forgot to respond to this. I'm not too familiar with the repr method, but this sounds like an awesome idea.

I made a table of what pre-processing is done for which models. I'm going to go through and standardize some of these, such that all models check for sample variable type, etc. OK to add a function to all models that automatically populates 0.0 values for oxides not passed?

Here is the current state of things:
<img width="887" alt="Screen Shot 2020-05-27 at 10 28 45 AM" src="https://user-images.githubusercontent.com/6538370/83040595-0ce77f00-a005-11ea-81c4-87017c8d2b5f.png">

**Comment by kaylai** [comment]
Closing this for now since we have done away with unnecessary pre-processing
