### ISSUE TITLE
Moore Water "calculate_dissolved_volatiles" discrepency as a function of pressure

### ISSUE THREAD

**Issue by PennyWieser** [kaylai/VESIcal#98]
I've run a synthetic dataset through Gordon's excel spreadsheet which calculates H2O(wt%) and compared it to calculate_dissolved_volatiles H2O. 

The discrepancy (e.g., spreadsheet value/Vesical) varies quite substantially as a function of pressure for two separate dummy tests (one with XH2O=1 at 1200C, one with XH2O=0.5 at 1000C). 
![image](https://user-images.githubusercontent.com/65668673/87024153-aa22ff00-c1d0-11ea-8157-6f2bb0bf218b.png)

 and

![image](https://user-images.githubusercontent.com/65668673/87024335-e0f91500-c1d0-11ea-8b29-52d82d2fd52c.png)

I've uploaded the scripts in the testing folder, Testing_Moore_et_al_1998.pynb and .xslx

**Comment by kaylai** [comment]
I think this is fixed. MooreWater was using the idealgas fugacity calculator, when it should have been using a Modified Redlich-Kwong. We already have an MRK in VESIcal, but I went ahead and coded up the exact one used in the Moore et al excel spreadsheet, for consistency. That is the Holloway and Blank version (fugacity_HB_h2o). Those two plots look much better now. I'm still not sure what the deal is with those four weirdo points at lowish P, but I spot them in your earlier plots too. At least the results are much better all around!

<img width="736" alt="Screen Shot 2020-07-16 at 5 24 33 PM" src="https://user-images.githubusercontent.com/6538370/87729103-306bb200-c78a-11ea-94f0-30dfae32f505.png">
<img width="726" alt="Screen Shot 2020-07-16 at 5 24 38 PM" src="https://user-images.githubusercontent.com/6538370/87729107-32357580-c78a-11ea-8035-a2e37ba5215e.png">


I'll close this for now, but Penny if you think there is more to be fixed or if other issues crop up related to this, feel free to reopen.

**Comment by kaylai** [comment]
Noting here, but I think nothing is wrong with the code so I am leaving the issue closed. I noticed that when changing the fugacity model to the correct one (per solution above), the fit between the experimental dataset and the calculated dataset appeared to become much worse. In fact, I double checked, and the plotted values are the same EXCEPT for additional points that are showing up in the higher pressure range when the correct fugacity model is used. Presumably, those samples were not returning values before and so those points didn't plot. Those higher-P points (which are above the calib range of the model) skew the fit. This is fine since those are above the calibration range, but I am noting this particularly for you, Penny, for when you go back and look at how the notebook performs now. See images below:

Original plot using fugacity_idealgas (incorrect):
<img width="539" alt="Screen Shot 2020-07-16 at 7 50 01 PM" src="https://user-images.githubusercontent.com/6538370/87736564-10de8480-c79e-11ea-91bb-30a2e659433a.png">

New plot using fugacity_HB_h2o (correct):
<img width="561" alt="HBh2o" src="https://user-images.githubusercontent.com/6538370/87736572-189e2900-c79e-11ea-8f97-e46477aa9bd8.png">
